sonar.host.url=https://sonarcloud.io
sonar.organization=paola-caric
sonar.projectKey=paola-caric_online-shop
sonar.projectName=OnlineShop
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
