sonar.host.url=https://sonarcloud.io
sonar.organization=YOUR_SONARCLOUD_ORG_KEY
sonar.projectKey=YOUR_PROJECT_KEY
sonar.projectName=Online Shop
sonar.java.source=21
sonar.sources=src/main/java
sonar.tests=src/test/java
