paypal.return-url=https://web-production-8a929.up.railway.app/checkout/paypal/return
paypal.cancel-url=https://web-production-8a929.up.railway.app/checkout
spring.h2.console.settings.web-allow-others=true
server.forward-headers-strategy=framework
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
